// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	test.proto
	test2.proto

It has these top-level messages:
	TestMessage
	LoginReq
	LoginAns
	EnterChReq
	EnterChAns
	EnterRmReq
	EnterRmAns
	PingReq
	PongAns
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// sample type
type TestType int32

const (
	TestType_TYPE_1 TestType = 0
	TestType_TYPE_2 TestType = 1
	TestType_TYPE_3 TestType = 2
)

var TestType_name = map[int32]string{
	0: "TYPE_1",
	1: "TYPE_2",
	2: "TYPE_3",
}
var TestType_value = map[string]int32{
	"TYPE_1": 0,
	"TYPE_2": 1,
	"TYPE_3": 2,
}

func (x TestType) Enum() *TestType {
	p := new(TestType)
	*p = x
	return p
}
func (x TestType) String() string {
	return proto.EnumName(TestType_name, int32(x))
}
func (x *TestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TestType_value, data, "TestType")
	if err != nil {
		return err
	}
	*x = TestType(value)
	return nil
}
func (TestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Error type
type ErrorCode int32

const (
	ErrorCode_ERR_SUCCESS       ErrorCode = 0
	ErrorCode_ERR_LOGIN_FAIL    ErrorCode = 1
	ErrorCode_ERR_ARGUMENT_FAIL ErrorCode = 2
)

var ErrorCode_name = map[int32]string{
	0: "ERR_SUCCESS",
	1: "ERR_LOGIN_FAIL",
	2: "ERR_ARGUMENT_FAIL",
}
var ErrorCode_value = map[string]int32{
	"ERR_SUCCESS":       0,
	"ERR_LOGIN_FAIL":    1,
	"ERR_ARGUMENT_FAIL": 2,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Msg_Id int32

const (
	Msg_Id_Login_Req    Msg_Id = 1
	Msg_Id_Login_Ans    Msg_Id = 2
	Msg_Id_Enter_Ch_Req Msg_Id = 3
	Msg_Id_Enter_Ch_Ans Msg_Id = 4
	Msg_Id_Enter_Rm_Req Msg_Id = 5
	Msg_Id_Enter_Rm_Ans Msg_Id = 6
	Msg_Id_Ping_Req     Msg_Id = 11
	Msg_Id_Pong_Ans     Msg_Id = 12
)

var Msg_Id_name = map[int32]string{
	1:  "Login_Req",
	2:  "Login_Ans",
	3:  "Enter_Ch_Req",
	4:  "Enter_Ch_Ans",
	5:  "Enter_Rm_Req",
	6:  "Enter_Rm_Ans",
	11: "Ping_Req",
	12: "Pong_Ans",
}
var Msg_Id_value = map[string]int32{
	"Login_Req":    1,
	"Login_Ans":    2,
	"Enter_Ch_Req": 3,
	"Enter_Ch_Ans": 4,
	"Enter_Rm_Req": 5,
	"Enter_Rm_Ans": 6,
	"Ping_Req":     11,
	"Pong_Ans":     12,
}

func (x Msg_Id) Enum() *Msg_Id {
	p := new(Msg_Id)
	*p = x
	return p
}
func (x Msg_Id) String() string {
	return proto.EnumName(Msg_Id_name, int32(x))
}
func (x *Msg_Id) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Msg_Id_value, data, "Msg_Id")
	if err != nil {
		return err
	}
	*x = Msg_Id(value)
	return nil
}
func (Msg_Id) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type TestMessage_SmallType int32

const (
	TestMessage_NORMAL TestMessage_SmallType = 0
	TestMessage_HARD   TestMessage_SmallType = 1
	TestMessage_HELL   TestMessage_SmallType = 2
)

var TestMessage_SmallType_name = map[int32]string{
	0: "NORMAL",
	1: "HARD",
	2: "HELL",
}
var TestMessage_SmallType_value = map[string]int32{
	"NORMAL": 0,
	"HARD":   1,
	"HELL":   2,
}

func (x TestMessage_SmallType) Enum() *TestMessage_SmallType {
	p := new(TestMessage_SmallType)
	*p = x
	return p
}
func (x TestMessage_SmallType) String() string {
	return proto.EnumName(TestMessage_SmallType_name, int32(x))
}
func (x *TestMessage_SmallType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TestMessage_SmallType_value, data, "TestMessage_SmallType")
	if err != nil {
		return err
	}
	*x = TestMessage_SmallType(value)
	return nil
}
func (TestMessage_SmallType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// sample struct
type TestMessage struct {
	TestString       *string                `protobuf:"bytes,1,req,name=testString" json:"testString,omitempty"`
	TestUint32       *uint32                `protobuf:"varint,2,req,name=testUint32" json:"testUint32,omitempty"`
	TestSmallType    *TestMessage_SmallType `protobuf:"varint,3,req,name=testSmallType,enum=msg.TestMessage_SmallType" json:"testSmallType,omitempty"`
	TestTestType     *TestType              `protobuf:"varint,4,opt,name=testTestType,enum=msg.TestType,def=0" json:"testTestType,omitempty"`
	TestBool         *bool                  `protobuf:"varint,5,req,name=testBool" json:"testBool,omitempty"`
	TestInt32        *int32                 `protobuf:"varint,6,req,name=testInt32" json:"testInt32,omitempty"`
	TestUint64       *uint64                `protobuf:"varint,7,opt,name=testUint64" json:"testUint64,omitempty"`
	TestFloat        *float32               `protobuf:"fixed32,8,opt,name=testFloat" json:"testFloat,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *TestMessage) Reset()                    { *m = TestMessage{} }
func (m *TestMessage) String() string            { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()               {}
func (*TestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_TestMessage_TestTestType TestType = TestType_TYPE_1

func (m *TestMessage) GetTestString() string {
	if m != nil && m.TestString != nil {
		return *m.TestString
	}
	return ""
}

func (m *TestMessage) GetTestUint32() uint32 {
	if m != nil && m.TestUint32 != nil {
		return *m.TestUint32
	}
	return 0
}

func (m *TestMessage) GetTestSmallType() TestMessage_SmallType {
	if m != nil && m.TestSmallType != nil {
		return *m.TestSmallType
	}
	return TestMessage_NORMAL
}

func (m *TestMessage) GetTestTestType() TestType {
	if m != nil && m.TestTestType != nil {
		return *m.TestTestType
	}
	return Default_TestMessage_TestTestType
}

func (m *TestMessage) GetTestBool() bool {
	if m != nil && m.TestBool != nil {
		return *m.TestBool
	}
	return false
}

func (m *TestMessage) GetTestInt32() int32 {
	if m != nil && m.TestInt32 != nil {
		return *m.TestInt32
	}
	return 0
}

func (m *TestMessage) GetTestUint64() uint64 {
	if m != nil && m.TestUint64 != nil {
		return *m.TestUint64
	}
	return 0
}

func (m *TestMessage) GetTestFloat() float32 {
	if m != nil && m.TestFloat != nil {
		return *m.TestFloat
	}
	return 0
}

// sample mseeage
type LoginReq struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginReq) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type LoginAns struct {
	Err              *ErrorCode `protobuf:"varint,1,req,name=err,enum=msg.ErrorCode" json:"err,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *LoginAns) Reset()                    { *m = LoginAns{} }
func (m *LoginAns) String() string            { return proto.CompactTextString(m) }
func (*LoginAns) ProtoMessage()               {}
func (*LoginAns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginAns) GetErr() ErrorCode {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ErrorCode_ERR_SUCCESS
}

type EnterChReq struct {
	ChNo             *uint32 `protobuf:"varint,1,req,name=chNo" json:"chNo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnterChReq) Reset()                    { *m = EnterChReq{} }
func (m *EnterChReq) String() string            { return proto.CompactTextString(m) }
func (*EnterChReq) ProtoMessage()               {}
func (*EnterChReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EnterChReq) GetChNo() uint32 {
	if m != nil && m.ChNo != nil {
		return *m.ChNo
	}
	return 0
}

type EnterChAns struct {
	Err              *ErrorCode `protobuf:"varint,1,req,name=err,enum=msg.ErrorCode" json:"err,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *EnterChAns) Reset()                    { *m = EnterChAns{} }
func (m *EnterChAns) String() string            { return proto.CompactTextString(m) }
func (*EnterChAns) ProtoMessage()               {}
func (*EnterChAns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EnterChAns) GetErr() ErrorCode {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ErrorCode_ERR_SUCCESS
}

type EnterRmReq struct {
	RmNo             *uint32 `protobuf:"varint,1,req,name=rmNo" json:"rmNo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnterRmReq) Reset()                    { *m = EnterRmReq{} }
func (m *EnterRmReq) String() string            { return proto.CompactTextString(m) }
func (*EnterRmReq) ProtoMessage()               {}
func (*EnterRmReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *EnterRmReq) GetRmNo() uint32 {
	if m != nil && m.RmNo != nil {
		return *m.RmNo
	}
	return 0
}

type EnterRmAns struct {
	Err              *ErrorCode `protobuf:"varint,1,req,name=err,enum=msg.ErrorCode" json:"err,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *EnterRmAns) Reset()                    { *m = EnterRmAns{} }
func (m *EnterRmAns) String() string            { return proto.CompactTextString(m) }
func (*EnterRmAns) ProtoMessage()               {}
func (*EnterRmAns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *EnterRmAns) GetErr() ErrorCode {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ErrorCode_ERR_SUCCESS
}

func init() {
	proto.RegisterType((*TestMessage)(nil), "msg.TestMessage")
	proto.RegisterType((*LoginReq)(nil), "msg.LoginReq")
	proto.RegisterType((*LoginAns)(nil), "msg.LoginAns")
	proto.RegisterType((*EnterChReq)(nil), "msg.EnterChReq")
	proto.RegisterType((*EnterChAns)(nil), "msg.EnterChAns")
	proto.RegisterType((*EnterRmReq)(nil), "msg.EnterRmReq")
	proto.RegisterType((*EnterRmAns)(nil), "msg.EnterRmAns")
	proto.RegisterEnum("msg.TestType", TestType_name, TestType_value)
	proto.RegisterEnum("msg.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("msg.Msg_Id", Msg_Id_name, Msg_Id_value)
	proto.RegisterEnum("msg.TestMessage_SmallType", TestMessage_SmallType_name, TestMessage_SmallType_value)
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x5f, 0x8b, 0x9b, 0x4c,
	0x14, 0xc6, 0xe3, 0xe4, 0xcf, 0x6b, 0x4e, 0x12, 0xdf, 0xe9, 0x40, 0x41, 0x42, 0x29, 0x83, 0x57,
	0x92, 0x16, 0xa1, 0x6e, 0x29, 0xb4, 0x57, 0xb5, 0xd6, 0x4d, 0x03, 0x26, 0xbb, 0x9c, 0x24, 0x17,
	0xbd, 0x92, 0xd0, 0x0c, 0x46, 0x88, 0xce, 0xae, 0x7a, 0xd3, 0xaf, 0xd0, 0x2f, 0xdb, 0xaf, 0x50,
	0x66, 0x36, 0xab, 0xe6, 0xae, 0xbd, 0x7b, 0xce, 0xef, 0x79, 0xe6, 0xd1, 0x33, 0x03, 0x50, 0x8b,
	0xaa, 0xf6, 0x1e, 0x4a, 0x59, 0x4b, 0xd6, 0xcf, 0xab, 0xd4, 0xf9, 0x4d, 0x60, 0xb2, 0x13, 0x55,
	0xbd, 0x16, 0x55, 0x75, 0x48, 0x05, 0x7b, 0xfd, 0x14, 0xd9, 0xd6, 0x65, 0x56, 0xa4, 0xb6, 0xc1,
	0x89, 0x3b, 0xc6, 0x0e, 0x79, 0xf6, 0xf7, 0x59, 0x51, 0xdf, 0xf8, 0x36, 0xe1, 0xc4, 0x9d, 0x61,
	0x87, 0xb0, 0xcf, 0x30, 0xd3, 0xe9, 0xfc, 0x70, 0x3e, 0xef, 0x7e, 0x3e, 0x08, 0xbb, 0xcf, 0x89,
	0x6b, 0xf9, 0x73, 0x2f, 0xaf, 0x52, 0xaf, 0xf3, 0x21, 0xaf, 0x49, 0xe0, 0xf5, 0x01, 0xf6, 0x11,
	0xa6, 0x0a, 0xa8, 0xac, 0x2e, 0x18, 0x70, 0xc3, 0xb5, 0xfc, 0x59, 0x53, 0xa0, 0xe0, 0xa7, 0xd1,
	0xee, 0xfb, 0x7d, 0x94, 0xbc, 0xc3, 0xab, 0x28, 0x9b, 0x83, 0xa9, 0xe6, 0x2f, 0x52, 0x9e, 0xed,
	0x21, 0x27, 0xae, 0x89, 0xcd, 0xcc, 0x5e, 0xc1, 0x58, 0xe9, 0x95, 0xfe, 0xef, 0x11, 0x27, 0xee,
	0x10, 0x5b, 0xd0, 0x5d, 0xeb, 0xc3, 0x7b, 0xfb, 0x3f, 0x6e, 0xb8, 0x03, 0xec, 0x90, 0xe7, 0xd3,
	0xb7, 0x67, 0x79, 0xa8, 0x6d, 0x93, 0x1b, 0x2e, 0xc1, 0x16, 0x38, 0x6f, 0x60, 0xdc, 0xfe, 0x3f,
	0xc0, 0x68, 0x73, 0x87, 0xeb, 0x20, 0xa6, 0x3d, 0x66, 0xc2, 0xe0, 0x5b, 0x80, 0x5f, 0xa9, 0xa1,
	0x55, 0x14, 0xc7, 0x94, 0x38, 0x73, 0x30, 0x63, 0x99, 0x66, 0x05, 0x8a, 0x47, 0x66, 0x01, 0xc9,
	0x8e, 0x97, 0x5b, 0x26, 0xd9, 0xd1, 0x79, 0x7b, 0xf1, 0x82, 0xa2, 0x62, 0x1c, 0xfa, 0xa2, 0x2c,
	0xb5, 0x69, 0xf9, 0x96, 0x5e, 0x3f, 0x2a, 0x4b, 0x59, 0x86, 0xf2, 0x28, 0x50, 0x59, 0x0e, 0x07,
	0x88, 0x8a, 0x5a, 0x94, 0xe1, 0x49, 0x75, 0x31, 0x18, 0xfc, 0x38, 0x6d, 0xa4, 0x3e, 0x30, 0x43,
	0xad, 0x1d, 0xaf, 0x49, 0xfc, 0x5b, 0x23, 0xe6, 0x97, 0xc6, 0x32, 0x6f, 0x1b, 0x95, 0x6e, 0x1a,
	0x31, 0xff, 0xab, 0xc6, 0x85, 0x07, 0x66, 0xf3, 0x3c, 0x00, 0x97, 0x67, 0xa3, 0xbd, 0x46, 0xfb,
	0xd4, 0x68, 0xf4, 0x0d, 0x25, 0x8b, 0x25, 0x8c, 0x9b, 0x06, 0xf6, 0x3f, 0x4c, 0x22, 0xc4, 0x64,
	0xbb, 0x0f, 0xc3, 0x68, 0xbb, 0xa5, 0x3d, 0xc6, 0xc0, 0x52, 0x20, 0xbe, 0x5b, 0xae, 0x36, 0xc9,
	0x6d, 0xb0, 0x8a, 0xa9, 0xc1, 0x5e, 0xc2, 0x0b, 0xc5, 0x02, 0x5c, 0xee, 0xd7, 0xd1, 0x66, 0xf7,
	0x84, 0xc9, 0xe2, 0x97, 0x01, 0xa3, 0x75, 0x95, 0x26, 0xab, 0x23, 0x9b, 0xc1, 0x58, 0xdf, 0x6a,
	0x82, 0xe2, 0x91, 0x1a, 0xed, 0x18, 0x14, 0x15, 0x25, 0x8c, 0xc2, 0x54, 0x6f, 0x94, 0x84, 0x27,
	0x1d, 0xe8, 0x5f, 0x11, 0x95, 0x19, 0xb4, 0x04, 0x73, 0x9d, 0x19, 0x5e, 0x11, 0x95, 0x19, 0xb1,
	0x29, 0x98, 0xf7, 0x59, 0x91, 0x6a, 0x7f, 0xa2, 0x27, 0x59, 0xa4, 0xda, 0x9b, 0xfe, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x57, 0xd1, 0xb6, 0x9e, 0x77, 0x03, 0x00, 0x00,
}
